### ISSUE TITLE
Issue with tzlocal==5.0

### ISSUE THREAD

**Issue by LFBianchi** [myusuf3/delorean#120]
Apparently the newest version of tzlocal (5.0) is causing an error on the parse function.

Python 3.9

Environment:
```
Delorean==1.0.0
tzlocal==5.0
```

Run:
```
from delorean import parse                                                                                                                                                                                                                                                                                                                      print(parse("2023-05-15T00:00:00.000Z", yearfirst=True, dayfirst=False))
```

Error:
```
AttributeError("'ZoneInfo' object has no attribute 'localize'")
```

If we change the environment to:
```
Delorean==1.0.0
tzlocal==4.3
```

The issue is resolved

**Comment by myusuf3** [comment]
Fixed. `parse()` works on tzlocal 5.4.4, which is what master resolves to now.
